### PR TITLE
Fix bad range req min chunksize

### LINKED ISSUE #73: BUG: downloads that do not use the standard chunksize in 0.2.0 and above result in broken files
0.2.0+ of pget results in broken files when/if a download is performed due to a miscalculation in the range-request.

### PR DESCRIPTION
**Pull request by tempusfrangit**
* Implement test to expose byte-range-request bug
* Implement fix to incorrect range-requests when maxChunks < fileSize / minChunkSize

Closes #73

### CODE REVIEW

File: pkg/download/buffer_unit_test.go [hunk 1]
```diff
@@ -64,6 +64,11 @@ func TestFileToBufferChunkCountExceedsMaxChunks(t *testing.T) {
 			minChunkSize: contentSize + 1,
 			maxChunks:    1,
 		},
+		{
+			name:         "minChunkSize equal to contentSize",
+			minChunkSize: contentSize,
+			maxChunks:    1,
+		},
```
Comment (tempusfrangit) [inline pkg/download/buffer_unit_test.go:71]: This is an additional edgecase that resulted in divide by zero errors.
